# Generated by Django 4.1.4 on 2022-12-07 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id_evento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_evento', models.CharField(max_length=250)),
                ('tipo_evento', models.CharField(max_length=250)),
                ('cupo_evento', models.IntegerField()),
                ('fecha_inicio_evento', models.DateField()),
                ('fecha_fin_evento', models.DateField()),
                ('direccion_evento', models.CharField(max_length=250)),
                ('descripcion_evento', models.TextField()),
                ('requisitos_evento', models.TextField()),
                ('estado_evento', models.CharField(max_length=250)),
                ('url_evento', models.CharField(max_length=250)),
            ],
        ),
    ]
