# Generated by Django 4.1.3 on 2022-12-06 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="evento",
            name="URL_form",
            field=models.CharField(default="", max_length=1500),
        ),
        migrations.AlterField(
            model_name="evento",
            name="tipo_evento",
            field=models.CharField(
                choices=[("T", "torneo"), ("M", "maraton"), ("Z", "zumba")],
                max_length=250,
            ),
        ),
    ]
